package com.tutorialspoint.helloworld;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-07-27T21:07:14.304+02:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://helloworld.tutorialspoint.com/", name = "HelloWorldPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldPortType {

    @WebMethod
    @RequestWrapper(localName = "greetings", targetNamespace = "http://helloworld.tutorialspoint.com/", className = "com.tutorialspoint.helloworld.Greetings")
    @ResponseWrapper(localName = "greetingsResponse", targetNamespace = "http://helloworld.tutorialspoint.com/", className = "com.tutorialspoint.helloworld.GreetingsResponse")
    @WebResult(name = "return", targetNamespace = "http://helloworld.tutorialspoint.com/")
    public java.lang.String greetings(

        @WebParam(name = "arg0", targetNamespace = "http://helloworld.tutorialspoint.com/")
        java.lang.String arg0
    );
}
