package com.tutorialspoint.helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-07-27T21:07:14.351+02:00
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "HelloWorldService",
                  wsdlLocation = "file:/C:/Users/AdamPC/Documents/Programont/programont/WSDL/src/main/resources/hello.wsdl",
                  targetNamespace = "http://helloworld.tutorialspoint.com/")
public class HelloWorldService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://helloworld.tutorialspoint.com/", "HelloWorldService");
    public final static QName HelloWorldPort = new QName("http://helloworld.tutorialspoint.com/", "HelloWorldPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/AdamPC/Documents/Programont/programont/WSDL/src/main/resources/hello.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/AdamPC/Documents/Programont/programont/WSDL/src/main/resources/hello.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HelloWorldService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldPortType getHelloWorldPort() {
        return super.getPort(HelloWorldPort, HelloWorldPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorldPort")
    public HelloWorldPortType getHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldPort, HelloWorldPortType.class, features);
    }

}
