//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.28 at 04:41:49 PM CEST 
//


package com.example;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PutDocumentRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PutDocumentRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Parameters" type="{java:hu.westel.estore.onlineif.bean}DocumentDescription" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProcessParameters" type="{java:hu.westel.estore.onlineif.bean}ProcessParameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ProcessType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Reason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RequestParameter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TransferType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PutDocumentRequest", namespace = "java:hu.westel.estore.onlineif.bean", propOrder = {
    "documentType",
    "parameters",
    "path",
    "processParameters",
    "processType",
    "reason",
    "requestParameter",
    "transferType",
    "userName"
})
public class PutDocumentRequest {

    @XmlElement(name = "DocumentType", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String documentType;
    @XmlElement(name = "Parameters", namespace = "java:hu.westel.estore.onlineif.bean", nillable = true)
    protected List<DocumentDescription> parameters;
    @XmlElement(name = "Path", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String path;
    @XmlElement(name = "ProcessParameters", namespace = "java:hu.westel.estore.onlineif.bean", nillable = true)
    protected List<ProcessParameter> processParameters;
    @XmlElement(name = "ProcessType", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String processType;
    @XmlElement(name = "Reason", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String reason;
    @XmlElement(name = "RequestParameter", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String requestParameter;
    @XmlElement(name = "TransferType", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String transferType;
    @XmlElement(name = "UserName", namespace = "java:hu.westel.estore.onlineif.bean", required = true, nillable = true)
    protected String userName;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentDescription }
     * 
     * 
     */
    public List<DocumentDescription> getParameters() {
        if (parameters == null) {
            parameters = new ArrayList<DocumentDescription>();
        }
        return this.parameters;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the processParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessParameter }
     * 
     * 
     */
    public List<ProcessParameter> getProcessParameters() {
        if (processParameters == null) {
            processParameters = new ArrayList<ProcessParameter>();
        }
        return this.processParameters;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessType(String value) {
        this.processType = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the requestParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestParameter() {
        return requestParameter;
    }

    /**
     * Sets the value of the requestParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestParameter(String value) {
        this.requestParameter = value;
    }

    /**
     * Gets the value of the transferType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferType() {
        return transferType;
    }

    /**
     * Sets the value of the transferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferType(String value) {
        this.transferType = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

}
