//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.15 at 10:34:26 AM CEST 
//


package com.example;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeZone }
     * 
     */
    public TimeZone createTimeZone() {
        return new TimeZone();
    }

    /**
     * Create an instance of {@link PutDocumentResponse }
     * 
     */
    public PutDocumentResponse createPutDocumentResponse() {
        return new PutDocumentResponse();
    }

    /**
     * Create an instance of {@link ListDocumentDataResponse }
     * 
     */
    public ListDocumentDataResponse createListDocumentDataResponse() {
        return new ListDocumentDataResponse();
    }

    /**
     * Create an instance of {@link DocumentData }
     * 
     */
    public DocumentData createDocumentData() {
        return new DocumentData();
    }

    /**
     * Create an instance of {@link DocumentDescription }
     * 
     */
    public DocumentDescription createDocumentDescription() {
        return new DocumentDescription();
    }

    /**
     * Create an instance of {@link ListDocumentDataRequest }
     * 
     */
    public ListDocumentDataRequest createListDocumentDataRequest() {
        return new ListDocumentDataRequest();
    }

    /**
     * Create an instance of {@link PutDocumentRequest }
     * 
     */
    public PutDocumentRequest createPutDocumentRequest() {
        return new PutDocumentRequest();
    }

    /**
     * Create an instance of {@link ProcessParameter }
     * 
     */
    public ProcessParameter createProcessParameter() {
        return new ProcessParameter();
    }

    /**
     * Create an instance of {@link GetDocumentRequest }
     * 
     */
    public GetDocumentRequest createGetDocumentRequest() {
        return new GetDocumentRequest();
    }

    /**
     * Create an instance of {@link InvalidateDocumentResponse }
     * 
     */
    public InvalidateDocumentResponse createInvalidateDocumentResponse() {
        return new InvalidateDocumentResponse();
    }

    /**
     * Create an instance of {@link InvalidateDocumentRequest }
     * 
     */
    public InvalidateDocumentRequest createInvalidateDocumentRequest() {
        return new InvalidateDocumentRequest();
    }

    /**
     * Create an instance of {@link DocumentIdentifier }
     * 
     */
    public DocumentIdentifier createDocumentIdentifier() {
        return new DocumentIdentifier();
    }

}
