spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/doctor
    username: testuser
    password : ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver